% combine solution tables

if ~exist('../out/sol-tab-combine','dir')
    mkdir('../out/sol-tab-combine');
end

for id = 1:120
    mkdir(['../out/sol-tab-combine/' sprintf('%03d',id)]);
    for c = 1:10 % unit procurement costs
        S1 = load(['../out/sol-tab/' sprintf('%03d',id) ...
                   '/sol-tab-abGm' sprintf('%03d',id) ...
                   '-c' sprintf('%d',c) ...
                   '-store1.mat'],'TabSol');
        S2 = load(['../out/sol-tab/' sprintf('%03d',id) ...
                   '/sol-tab-abGm' sprintf('%03d',id) ...
                   '-c' sprintf('%d',c) ...
                   '-store2.mat'],'TabSol');
        S3 = load(['../out/sol-tab/' sprintf('%03d',id) ...
                   '/sol-tab-abGm' sprintf('%03d',id) ...
                   '-c' sprintf('%d',c) ...
                   '-store3.mat'],'TabSol');

        TabSol = zeros([size(S1.TabSol) 3]); 
        TabSol(:,:,1) = S1.TabSol;
        TabSol(:,:,2) = S2.TabSol;
        TabSol(:,:,3) = S3.TabSol;
        clear S1 S2 S3
        
        save(['../out/sol-tab-combine/' sprintf('%03d',id) ...
              '/sol-tab-abGm' sprintf('%03d',id) ...
              '-c' sprintf('%d',c) '.mat'],'TabSol')
    end
end